language: python
matrix:
  include:
    - python: 3.6
      sudo: true
      dist: xenial
    - python: 3.7
      sudo: true
      dist: xenial
install:
  - pip install --upgrade mypy
  - pip install -r requirements.txt . coveralls
script:
  - echo "running unit tests"
  - coverage run --source="./src/qilib" -m unittest discover -s src/tests -t src -v
  - echo "running mypy"
after_success:
  - coveralls
deploy:
  provider: pypi
  user: qinspire
  password:
    secure: zJ3IyRXxmF+ZpY4fH9cMyPkYyaPAQ5SGV8BalZ0wBk5bru0eY+EM21P0hEa7U9ujn6ez8smFdu247z1UNlq9iklTu3r9p0Ht6PZkG3+R12B2+EiniPFdqXPUyDxyxzsvnzv7+mRT6y/QlyZ5dgljE4a7GUkzmBp9G0FJa4gPUN+H2yg0vSM7MQvuVFvEFwkJbBKFuWGIZXNK6MmwIYqI8mPC8r680g99du3HHvsM05zKagdAFQfhA0D5iOFo2VmsWlhZBmdQnM2zyl78O7vgOmlP4vM+JCb+ewVPCXPASVExJf2xVaTTZ+A8ehGFw7MFHhMVeHsRVrGxZZrCPrpaMvOT2SA51+knEiCeRDF/kyD1SoXXOStODREJnOo2WwE9K5eDqMQ2YPNOKfI+cn83Iqx9xea4azJsyFFvtyY5PVY4JG0MJQfld4UQ0y25OhT1S7Pkk2ghFJpr3qL937/En4Y77gci7Xk+57vDBt+aInopH7InkFW06AzIp/7oBF7UlEuelFRUlzlj/04ZKEN4/9uwUaeiO/HJyTqLQ0qpMdc+fVWfvoSSRYaZFbkE7+DURHEvvDyY1JP5fCmO/7mfVo0G4ouzbt9s+Ls8x86TH6rd3FWnKBc0Z1QPPcBS/p1xDJVwg/0PvC+ZvpuYd6riqmnVtNGjP4j+Flt3/LkfcNM=
  on:
    tags: true
    branch: master
  skip_existing: true
